[server]
host = "0.0.0.0"
port = 8080

[cors]
enabled = true
allow_origins = ["*"]

[logging]
level = "info"

[solana]
# Production environment Solana configuration
rpc_url = "http://localhost:8899"
ws_url = "ws://localhost:8900"
# Please replace with the actual Spin Pet program ID
program_id = "JBMmrp6jhksqnxDBskkmVvWHhJLaPBjgiMHEroJbUTBZ"
# Event listener configuration
enable_event_listener = true
commitment = "confirmed"  # processed/confirmed/finalized
reconnect_interval = 10000  # Longer reconnect interval for production
max_reconnect_attempts = 20
# Event processing configuration
event_buffer_size = 2000
event_batch_size = 200 